<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RuntimeIdentifiers>linux-x64</RuntimeIdentifiers>
    <UserSecretsId>64f791a2-f79b-4034-93f4-0b972c0f9e1c</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cabinet.Domain\Cabinet.Domain.csproj" />
    <ProjectReference Include="..\Cabinet.Repository\Cabinet.Repository.csproj" />
  </ItemGroup>

</Project>
