<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RuntimeIdentifiers>linux-x64</RuntimeIdentifiers>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp" Version="4.153.1" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="4.153.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cabinet.Domain\Cabinet.Domain.csproj" />
  </ItemGroup>

</Project>
